#
# This source file is part of the SpeziFileFormats open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-iOS.xcresult
      artifactname: SpeziFileFormats-iOS.xcresult
  packagewatchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: SpeziFileFormats-watchOS.xcresult
      artifactname: SpeziFileFormats-watchOS.xcresult
  packagevisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziFileFormats-visionOS.xcresult
      artifactname: SpeziFileFormats-visionOS.xcresult
  packagetvos:
    name: Build and Test Swift Package tvOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-tvOS.xcresult
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      artifactname: SpeziFileFormats-tvOS.xcresult
  packagemacos:
    name: Build and Test Swift Package macOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      xcodeversion: latest
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziFileFormats-macOS.xcresult
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      codeql: true
      test: false
      scheme: SpeziFileFormats-Package
    permissions:
      security-events: write
      actions: read
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, packagewatchos, packagevisionos, packagetvos, packagemacos, ios, ipados, watchos, visionos, tvos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziFileFormats-iOS.xcresult SpeziFileFormats-watchOS.xcresult SpeziFileFormats-visionOS.xcresult SpeziFileFormats-tvOS.xcresult SpeziFileFormats-macOS.xcresult TestApp-iOS.xcresult TestApp-iPadOS.xcresult TestApp-watchOS.xcresult TestApp-visionOS.xcresult TestApp-tvOS.xcresult TestAppMacOS.xcresult