#
# This source file is part of the SpeziFileFormats open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-iOS.xcresult
      artifactname: SpeziFileFormats-iOS.xcresult
  watchos:
    name: Build and Test Swift Package watchOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      destination: 'platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)'
      resultBundle: SpeziFileFormats-watchOS.xcresult
      artifactname: SpeziFileFormats-watchOS.xcresult
  visionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      scheme: SpeziFileFormats-Package
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
      resultBundle: SpeziFileFormats-visionOS.xcresult
      artifactname: SpeziFileFormats-visionOS.xcresult
  tvos:
    name: Build and Test Swift Package tvOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-tvOS.xcresult
      destination: 'platform=tvOS Simulator,name=Apple TV 4K (3rd generation)'
      artifactname: SpeziFileFormats-tvOS.xcresult
  macos:
    name: Build and Test Swift Package macOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      xcodeversion: latest
      scheme: SpeziFileFormats-Package
      resultBundle: SpeziFileFormats-macOS.xcresult
      destination: 'platform=macOS,arch=arm64'
      artifactname: SpeziFileFormats-macOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [ios, watchos, visionos, tvos, macos]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@fix/codecov-v4
    with:
      coveragereports: SpeziFileFormats-iOS.xcresult SpeziFileFormats-watchOS.xcresult SpeziFileFormats-visionOS.xcresult SpeziFileFormats-tvOS.xcresult SpeziFileFormats-macOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}